language: en
max_retries: 5
gcp_project: soges-group-data-platform
log_level: INFO

embed_metadata: True
embedding_api_base: http://192.168.178.82:11434
embedding_model: hf.co/nomic-ai/nomic-embed-text-v1.5-GGUF:F32

main_model:
  name: gemini-2.5-pro
  temperature: 0.0
  # top_k: 20
  # top_p: 20

rerank_metadata: True
rerank_model:
  name: gemini-2.5-flash
  temperature: 0.0

answer_model:
  name: gemini-2.5-flash
  temperature: 0.0
